export const sectors = [
  { value: "Agriculture", label: "Agriculture" },
  { value: "Arts", label: "Arts" },
  { value: "Construction", label: "Construction" },
  { value: "Consumer Goods", label: "Consumer Goods" },
  { value: "Corporate Services", label: "Corporate Services" },
  { value: "Design", label: "Design" },
  { value: "Education", label: "Education" },
  { value: "Energy & Mining", label: "Energy & Mining" },
  { value: "Entertainment", label: "Entertainment" },
  { value: "Finance", label: "Finance" },
  { value: "Hardware & Networking", label: "Hardware & Networking" },
  { value: "Health Care", label: "Health Care" },
  { value: "Legal", label: "Legal" },
  { value: "Manufacturing", label: "Manufacturing" },
  { value: "Media & Communications", label: "Media & Communications" },
  { value: "Nonprofit", label: "Nonprofit" },
  { value: "Public Administration", label: "Public Administration" },
  { value: "Public Safety", label: "Public Safety" },
  { value: "Real Estate", label: "Real Estate" },
  { value: "Recreation & Travel", label: "Recreation & Travel" },
  { value: "Retail", label: "Retail" },
  { value: "Software & IT Services", label: "Software & IT Services" },
  { value: "Transportation & Logistics", label: "Transportation & Logistics" },
  { value: "Wellness & Fitness", label: "Wellness & Fitness" }
];