// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Experience struct {
	Title        string  `json:"title"`
	IsCurrent    bool    `json:"isCurrent"`
	StartDate    string  `json:"startDate"`
	EndDate      *string `json:"endDate,omitempty"`
	Achievements string  `json:"achievements"`
}

type ExperienceInput struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	IsCurrent    bool    `json:"isCurrent"`
	StartDate    string  `json:"startDate"`
	EndDate      *string `json:"endDate,omitempty"`
	Achievements string  `json:"achievements"`
}

type JobPosting struct {
	Title        string  `json:"title"`
	Company      string  `json:"company"`
	Requirements string  `json:"requirements"`
	AddOn        *string `json:"addOn,omitempty"`
}

type JobPostingInput struct {
	Title        string  `json:"title"`
	Company      string  `json:"company"`
	Requirements string  `json:"requirements"`
	AddOn        *string `json:"addOn,omitempty"`
}

type Profile struct {
	ID          string        `json:"id"`
	UserBio     *UserBio      `json:"userBio"`
	JobPosting  *JobPosting   `json:"jobPosting"`
	Experiences []*Experience `json:"experiences"`
}

type ProfileInput struct {
	ID          string             `json:"id"`
	UserBio     *UserBioInput      `json:"userBio"`
	JobPosting  *JobPostingInput   `json:"jobPosting"`
	Experiences []*ExperienceInput `json:"experiences"`
}

type UserBio struct {
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Email     string   `json:"email"`
	Phone     []string `json:"phone"`
	Address   string   `json:"address"`
}

type UserBioInput struct {
	FirstName string   `json:"firstName"`
	LastName  string   `json:"lastName"`
	Email     string   `json:"email"`
	Phone     []string `json:"phone"`
	Address   string   `json:"address"`
}
