# fly.toml app configuration file generated for llama-index on 2023-10-09T14:04:30+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "llama-index"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 5601
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
