name: Deploy Backend Staging
on:
  push:
    branches-ignore:
      - main
    paths:
      - platform/main/**
      - .github/workflows/backend-staging.yaml
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    container:
      image: birudeghi/cvhq:latest
      ports:
        - 8080
    defaults:
      run:
        working-directory: ./platform/main
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl secrets set APP_ENV=$APP_DEMO_ENV OPENAI_KEY=${{ secrets.OPENAI_KEY }} AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} -t ${{ secrets.FLY_API_TOKEN_CVHQ }} --config ./fly.staging.toml
      - run: flyctl deploy --remote-only -t ${{ secrets.FLY_API_TOKEN_CVHQ }} --config ./fly.staging.toml